# https://docs.drone.io/quickstart/docker/
# https://docs.drone.io/pipeline/docker/examples/languages/csharp/

kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
