# Main page:
#  * https://drone.ci.nibblepoker.lu/aziascreations/DotNet-Arguments

# Documentation:
#  * https://docs.drone.io/quickstart/docker/
#  * https://docs.drone.io/pipeline/docker/examples/languages/csharp/
#  * https://discourse.drone.io/t/builds-are-stuck-in-pending-status/4437

kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
  commands:
  - dotnet build
  - dotnet test
