var classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions =
[
    [ "ArgumentsException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1ArgumentsException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1ArgumentsException" ],
    [ "DuplicateOptionException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1DuplicateOptionException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1DuplicateOptionException" ],
    [ "DuplicateVerbException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1DuplicateVerbException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1DuplicateVerbException" ],
    [ "ExistingDefaultMultipleOptionException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1ExistingDefaultMultipleOptionException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1ExistingDefaultMultipleOptionException" ],
    [ "InvalidArgumentException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1InvalidArgumentException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1InvalidArgumentException" ],
    [ "InvalidFlagsException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1InvalidFlagsException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1InvalidFlagsException" ],
    [ "InvalidVerbNameException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1InvalidVerbNameException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1InvalidVerbNameException" ],
    [ "MissingOptionIdentifierException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1MissingOptionIdentifierException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1MissingOptionIdentifierException" ],
    [ "MissingRequiredOptionException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1MissingRequiredOptionException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1MissingRequiredOptionException" ],
    [ "NoDefaultOptionFoundException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1NoDefaultOptionFoundException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1NoDefaultOptionFoundException" ],
    [ "NotEnoughArgumentsException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1NotEnoughArgumentsException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1NotEnoughArgumentsException" ],
    [ "OptionException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1OptionException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1OptionException" ],
    [ "OptionHasValueAndMoreShortsException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1OptionHasValueAndMoreShortsException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1OptionHasValueAndMoreShortsException" ],
    [ "OptionValueOverflowException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1OptionValueOverflowException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1OptionValueOverflowException" ],
    [ "ParserException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1ParserException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1ParserException" ],
    [ "RepeatedSingularOptionException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1RepeatedSingularOptionException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1RepeatedSingularOptionException" ],
    [ "UnknownOptionException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1UnknownOptionException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1UnknownOptionException" ],
    [ "VerbException", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1VerbException.html", "classNibblePoker_1_1Library_1_1Arguments_1_1Exceptions_1_1VerbException" ]
];