name: GitHub Pages

on:
  push:
    branches:
      - master
      - dev-cicd-and-c99-catchup
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    concurrency:
      group: cicd-docs
    
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Install .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install DocFX
        run: |
          dotnet tool install -g docfx

      - name: Copy Markdown files
        run: |
          sudo cp readme.md NibblePoker.Library.Arguments.Documentation/index.md
          sudo cp building.md NibblePoker.Library.Arguments.Documentation/building.md
      
      - name: Build DocFX documentation
        working-directory: NibblePoker.Library.Arguments.Documentation
        run: |
          docfx build ./docfx.json
        continue-on-error: false
        
      - name: Fix API index
        working-directory: NibblePoker.Library.Arguments.Documentation
        run: |
          sudo rm _site/api/index.html
          sudo cp _site/api/NibblePoker.Library.Arguments.html _site/api/index.html
        continue-on-error: true

      - name: Deploy documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./NibblePoker.Library.Arguments/_site
