name: NUnit Tests

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  do-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Install .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      
      - name: Run NUnit tests
        run: | 
          dotnet test ./
